version: "3"
services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - ":4444:4444"
    volumes:
      - "/home/linky:/etc/selenoid/" # assumed current dir contains browsers.json                                                                 n
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/linky/video:/opt/selenoid/video" # change to your video save path
      - "/home/linky/logs:/opt/selenoid/logs" # change to your logs save path
    environment:
      OVERRIDE_VIDEO_OUTPUT_DIR: /home/linky/video
    command:
      [
        "-log-output-dir",
        "/opt/selenoid/logs",
        "-conf",
        "/etc/selenoid/browsers.json",
        "-capture-driver-logs",
        "-limit",
        "9",
        "-listen",
        ":4444"
      ]

  selenoid-ui-ggr:
    image: "aerokube/selenoid-ui"
    depends_on:
      - selenoid
    network_mode: bridge
    links:
      - selenoid
    ports:
      - ":8081:8081"
    command: ["--selenoid-uri", "http://<internal_container_ip>:8888","-listen",":8081"]

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    depends_on:
      - selenoid
    network_mode: bridge
    links:
      - selenoid
    ports:
      - ":8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  allure:
    image: "frankescobar/allure-docker-service"
    user: root
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 15
      KEEP_HISTORY: "TRUE"
      KEEP_HISTORY_LATEST: 25
      SECURITY_USER: ""
      SECURITY_PASS: ""
      SECURITY_ENABLED: 1
    ports:
      - ":5050:5050"
    volumes:
      - "/home/linky/allure-results:/app/allure-results"
      - "/home/linky/allure-reports:/app/default-reports"
      - "/home/linky/allure-projects:/app/projects"

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    user: root
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
    ports:
      - ":5252:5252"
